delete from subaddress_src;
INSERT INTO subaddress_src
(OBJECTID, SUB_ADDRESS_ID, MELISSA_SUITE, AP_ID, ADDITIONAL_LOC_INFO, BUILDING, FLOOR, UNIT, ROOM, SEAT, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, GLOBALID, BOROUGHCODE, VALIDATION_DATE, UPDATE_SOURCE, USPS_HNUM)
VALUES(415433, 415433, 'APT 3', 3006230, NULL, NULL, NULL, 'APT 3', NULL, NULL, NULL, NULL, NULL, NULL, '{7C0AC2E2-089F-42F4-871B-EA35233AC142}', '3', NULL, NULL, NULL);
INSERT INTO subaddress_src
(OBJECTID, SUB_ADDRESS_ID, MELISSA_SUITE, AP_ID, ADDITIONAL_LOC_INFO, BUILDING, FLOOR, UNIT, ROOM, SEAT, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, GLOBALID, BOROUGHCODE, VALIDATION_DATE, UPDATE_SOURCE, USPS_HNUM)
VALUES(751227, 751227, 'APT 1', 3006230, NULL, NULL, NULL, 'APT 1', NULL, NULL, NULL, NULL, NULL, NULL, '{E6B91B19-94B3-49DD-B821-A8077BC9C96A}', '3', NULL, NULL, NULL);
INSERT INTO subaddress_src
(OBJECTID, SUB_ADDRESS_ID, MELISSA_SUITE, AP_ID, ADDITIONAL_LOC_INFO, BUILDING, FLOOR, UNIT, ROOM, SEAT, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, GLOBALID, BOROUGHCODE, VALIDATION_DATE, UPDATE_SOURCE, USPS_HNUM)
VALUES(751228, 751228, 'BSMT', 3006230, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{ABB3A520-AD57-46D6-A31E-FCC0C3A093CB}', '3', NULL, NULL, NULL);
INSERT INTO subaddress_src
(OBJECTID, SUB_ADDRESS_ID, MELISSA_SUITE, AP_ID, ADDITIONAL_LOC_INFO, BUILDING, FLOOR, UNIT, ROOM, SEAT, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, GLOBALID, BOROUGHCODE, VALIDATION_DATE, UPDATE_SOURCE, USPS_HNUM)
VALUES(1793472, 1793472, 'APT 2', 3006230, NULL, NULL, NULL, 'APT 2', NULL, NULL, NULL, NULL, NULL, NULL, '{DB13F16F-4A8A-4AD2-8CFB-5F1B436A32C4}', '3', NULL, NULL, NULL);
commit;