CREATE OR REPLACE PACKAGE CSCL_SUBADDRESS
AUTHID CURRENT_USER
AS

    FUNCTION DUMMY (
        p_dummy         IN VARCHAR2
    ) RETURN VARCHAR2 DETERMINISTIC;

    

END CSCL_SUBADDRESS;
/

CREATE OR REPLACE PACKAGE BODY CSCL_SUBADDRESS
AS

    FUNCTION DUMMY (
        p_dummy         IN VARCHAR2
    ) RETURN VARCHAR2 DETERMINISTIC
    AS
    
        retval          VARCHAR2(1) := 'X';

    BEGIN

        RETURN retval;

    END DUMMY;
       

END CSCL_SUBADDRESS;
/
